FROM ruby:3.0.2-alpine3.14

LABEL name=demo-app
ENV INSTALL_PATH=/app/ \
    BUNDLE_PATH=vendor/bundle \
    SECRET_KEY_BASE=6a12da0330246c126f5d6a2486b707033f2223745a0d08884785e298fb86357b064f0aaa11af69a22209c08652023626991e478314a2104e9505fef962d123ba \
    REDIS_PROVIDER=REDIS_URL \
    RAILS_SERVE_STATIC_FILES=true \
    PORT=80

RUN rm -rf /var/cache/apk/* \
  && rm -rf /tmp/* \
  && apk update

RUN apk add --no-cache build-base yarn nodejs tzdata libxslt-dev libxml2-dev mariadb-dev

RUN gem install bundler \
  && gem install foreman

WORKDIR $INSTALL_PATH

EXPOSE $PORT

CMD tail -f /dev/null

