#!/bin/sh
set -e

mysql --verbose -uroot -p$MYSQL_ROOT_PASSWORD <<ADDTEXT
CREATE USER '${MYSQL_TEST_USER}'@'%' IDENTIFIED BY '${MYSQL_TEST_PASSWORD}' ;
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_TEST_USER'@'%';
FLUSH PRIVILEGES;
ADDTEXT
